[package]
name = "exam"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
bigint = "4.4.3"
clap = { version = "4.5.23", features = ["derive"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.8.5"
sha2 = "0.10.8"
